package main.se450.model;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import main.se450.collections.LineCollection;
import main.se450.constants.ShapeSize;
import main.se450.interfaces.IDebris;
import main.se450.singletons.ConfigurationManager;
import main.se450.singletons.DisplayManager;
import main.se450.strategies.PassThruStrategy;

/**
 * The Class DebrisPoint represent debris point object that generated by
 * destroying a small size shape.
 */
public class DebrisPoint extends Circle implements IDebris {

	/** The circle. */
	private Ellipse2D circle = new Ellipse2D.Float(0.0f, 0.0f, 0.0f, 0.0f);

	/** The life time. */
	private int lifeTime = 0;

	/**
	 * Instantiates a new debris point object.
	 *
	 * @param nLeft
	 *            The minimum X coordinate of the new shape
	 * @param nTop
	 *            The minimum Y coordinate of the new shape
	 * @param nRight
	 *            The maximum X coordinate of the new shape
	 * @param nBottom
	 *            The maximum Y coordinate of the new shape
	 * @param nX
	 *            The speed in X direction of the new shape
	 * @param nY
	 *            The speed in Y direction of the new shape
	 * @param nRotation
	 *            The speed of rotation of the new shape
	 * @param cColor
	 *            The color of the new shape
	 */
	public DebrisPoint(float nLeft, float nTop, float nRight, float nBottom, float nX, float nY, float nRotation,
			Color cColor) {
		super(nLeft, nTop, nRight, nBottom, nX, nY, nRotation, cColor,
				new PassThruStrategy(DisplayManager.getDisplayManager().getDimension()), ShapeSize.SMALL, 0, 0, 0);

		lifeTime = ConfigurationManager.getConfigurationManager().getConfiguration().getShotLifetime();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see main.se450.model.Circle#draw(java.awt.Graphics)
	 */
	@Override
	public void draw(Graphics g) {
		circle.setFrame(getMinX(), getMinY(),
				ConfigurationManager.getConfigurationManager().getConfiguration().getShotDiameter(),
				ConfigurationManager.getConfigurationManager().getConfiguration().getShotDiameter());

		Graphics2D g2d = (Graphics2D) g;

		g2d.setColor(getColor());
		g2d.fill(circle);
		g2d.draw(circle);
	}

	/**
	 * Decrease life time value when updating.
	 * 
	 * @see main.se450.model.ShapeDroid#update()
	 */
	@Override
	public void update() {
		--lifeTime;

		super.update();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see main.se450.interfaces.IDebris#isExpired()
	 */
	@Override
	public boolean isExpired() {
		return (lifeTime < 0);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see main.se450.model.Shape#getLineCollection()
	 */
	@Override
	public LineCollection getLineCollection() {
		return super.getLineCollection();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see main.se450.interfaces.IDebris#setFrame(float, float)
	 */
	@Override
	public void setFrame(float minX, float minY) {

	}
}
